### ISSUE TITLE
More details about apache in the wiki?

### ISSUE THREAD

**Issue by mlocati** [lemonbrain-mk/graphql_websocket#13]
What about adding these lines to https://github.com/lemonbrain-mk/graphql_websocket/wiki/2.-Apache (right after "What you have to do that apache handles websockets. The following code needs Apache >2.4, and the modules mod_proxy_wstunnel and mod_proxy enabled.")?

> To enable those two modules, simply add these two lines to your apache configuration file:
> ```
> LoadModule proxy_module modules/mod_proxy.so
> LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
> ```

**Comment by marcokuoni** [comment]
I put it in the wiki, but i think there would be also other ways to enable it. Something similar to `a2enmod proxy_wstunnel` or so. But for sure not bad to show a possible way.
