### ISSUE TITLE
Include enum, scalar, interface, fragment, input, union to the merge system

### ISSUE THREAD

**Issue by marcokuoni** [lemonbrain-mk/graphql_websocket#4]
At the moment it looks for all type objects: merges all query, mutation and subscriptions together. And throws a error if a type is found two time except of this three from before. so makes sense to this not just with type objects also with all other posible objects in a schema file https://graphql.github.io/graphql-spec/draft/#sec-Type-System

**Comment by lemonbrain-mk** [comment]
Duplicate of #5

**Comment by marcokuoni** [comment]
Duplicate of #5
